# Generated by Django 5.2.7 on 2026-03-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobhostsummary",
            name="host_name",
            field=models.CharField(db_index=True, help_text="Host name for display (from AWX)", max_length=512),
        ),
    ]
